find_path(JERRYSCRIPT_INCLUDE_DIR NAMES jerryscript.h PATHS ${CONAN_INCLUDE_DIRS_JERRYSCRIPT})
find_library(JERRYSCRIPT_CORE_LIBRARY NAMES jerry-core PATHS ${CONAN_LIB_DIRS_JERRYSCRIPT})
find_library(JERRYSCRIPT_EXT_LIBRARY NAMES jerry-ext PATHS ${CONAN_LIB_DIRS_JERRYSCRIPT})
find_library(JERRYSCRIPT_PORT_DEFAULT_LIBRARY NAMES jerry-port-default PATHS ${CONAN_LIB_DIRS_JERRYSCRIPT})

add_library(JerryScript::core INTERFACE IMPORTED)
set_target_properties(JerryScript::core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ${JERRYSCRIPT_INCLUDE_DIR}
  INTERFACE_LINK_LIBRARIES ${JERRYSCRIPT_CORE_LIBRARY}
)

add_library(JerryScript::ext INTERFACE IMPORTED)
set_target_properties(JerryScript::ext PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ${JERRYSCRIPT_INCLUDE_DIR}
  INTERFACE_LINK_LIBRARIES ${JERRYSCRIPT_EXT_LIBRARY}
)

add_library(JerryScript::port_default INTERFACE IMPORTED)
set_target_properties(JerryScript::port_default PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ${JERRYSCRIPT_INCLUDE_DIR}
  INTERFACE_LINK_LIBRARIES ${JERRYSCRIPT_PORT_DEFAULT_LIBRARY}
)

mark_as_advanced(
  JERRYSCRIPT_INCLUDE_DIR
  JERRYSCRIPT_CORE_LIBRARY
  JERRYSCRIPT_EXT_LIBRARY
  JERRYSCRIPT_PORT_DEFAULT_LIBRARY
)

message("** JerryScript found by Conan!")
set(JERRYSCRIPT_FOUND TRUE)
message("   - includes: ${JERRYSCRIPT_INCLUDE_DIR}")
message("   - core libraries ${JERRYSCRIPT_CORE_LIBRARY}")
message("   - ext libraries ${JERRYSCRIPT_EXT_LIBRARY}")
message("   - port default libraries ${JERRYSCRIPT_PORT_DEFAULT_LIBRARY}")
